### PR TITLE
add your own redirect_uri in get_authorization_url

### PR DESCRIPTION
**Pull request by PhoenixAlx**
I have added this beacause  you could to use to own url (django things, in example...)

### CODE REVIEW

**Comment by alejcas** [comment]
Then you have to pass the redirect_url to the OAuth2Session, because your change has no effect.

Can you fix it so I can merge this PR?

**Comment by PhoenixAlx** [comment]
uhm @janscas the question is that I do the next:

account = O365.Account(credentials, auth_method='oauth',scopes=scopes)
myurl="link"
url = account.connection.get_authorization_url(redirect_uri=myurl)

How could I add myurl to OAuth2Session?

**Comment by alejcas** [comment]
> How could I add myurl to OAuth2Session?

In your commit you modified the function signature by adding the redirect_uri parameter. That's ok, but not enough:

`def get_authorization_url(self, requested_scopes=None, redirect_uri=OAUTH_REDIRECT_URL):`

You have to pass the new parameter to the Oauth2Session, so instead:

`self.session = oauth = OAuth2Session(client_id=client_id, redirect_uri=OAUTH_REDIRECT_URL, scope=scopes)`

do:

`self.session = oauth = OAuth2Session(client_id=client_id, redirect_uri=redirect_uri, scope=scopes)`

**Comment by PhoenixAlx** [comment]
aaaah, It's true. I understand now, thanks. I forgot that sorry

**Pull request merged**
